# https://taskfile.dev

version: '3'

vars:
  DOCKER_IMAGE_NAME: local/partnerincare
  DOCKER_CONTAINER_NAME: partnerincare

tasks:
  build-image:
    cmds:
      - docker build -t {{.DOCKER_IMAGE_NAME}} .

  build-image-nocache:
    cmds:
      - docker build --no-cache -t {{.DOCKER_IMAGE_NAME}} .

  env-run:
    interactive: true
    cmds:
      - |
        docker run --rm -it \
        -v $(pwd):/app \
        -p 8000 \
        --name {{.DOCKER_CONTAINER_NAME}} \
        -w /app \
        {{.DOCKER_IMAGE_NAME}} /bin/bash

  env-term:
    interactive: true
    cmds:
      - |
        docker exec -it \
        {{.DOCKER_CONTAINER_NAME}} \
        /bin/bash
